app_back:
    resource: "@AppBackBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
app_user:
    resource: "@AppUserBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /admin
