app_api:
    resource: "@AppApiBundle/Controller/"
    type:     annotation
    prefix:   /api

app_blog:
    resource: "@AppBlogBundle/Controller/"
    type:     annotation
    prefix:   /

app_back:
    resource: "@AppBackBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
app_user:
    resource: "@AppUserBundle/Controller/"
    type:     annotation
    prefix:   /admin
    
# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /admin